//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VTS.rc
//
#define IDC_BUTTON_REGISTER_NEW         3
#define IDCANCEL2                       3
#define IDC_BUTTON_ALL                  3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PROPPAGE_WITHDRAW_REQUEST   102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_CURSOR_ORDER_CORRECTION     105
#define IDC_CURSOR_ORDER_CANCEL         106
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_VTSTYPE                     130
#define ID_WINDOW_MANAGER               131
#define IDR_PASTE_MENU                  151
#define ID_SET_STYLE                    201
#define IDS_EDIT_MENU                   306
#define ID_VIEW_MENUBAR                 312
#define IDD_DIALOG_RECOMMENDERS_CLIENT_INFO 312
#define IDB_HIGH                        313
#define IDB_LOW                         314
#define IDD_DIALOG_DUMMY_TEST           314
#define IDB_OPEN                        315
#define ID_VIEW_UI_LOOK_BAR             315
#define IDD_DIALOG_RECOMMENDER_MEMBERS_PROFIT 316
#define ID_WINDOWS_LIST                 316
#define IDD_DIALOG1                     318
#define IDD_DIALOG_REGISTER             319
#define IDD_PROPPAGE_DEPOSIT_REQUEST    322
#define IDD_DIALOG_DEPOSIT_REQUEST      322
#define IDD_DIALOG_NOTICES              324
#define IDD_DIALOG_ORDER_HISTORY        325
#define IDD_DIALOG_EACHDAY_PROFIT       326
#define IDD_DIALOG_BANKING_HISTORY      327
#define IDD_DIALOG_USER_ACTION_LOG      328
#define IDB_BITMAP_VTS                  329
#define IDB_HOGA_C                      343
#define IDB_HOGA_CONTRACT               343
#define IDB_HOGA_CONTRACT_BUY           343
#define IDD_DIALOG_FUTURES_CODE         349
#define IDR_MAIN_TOOLBAR                354
#define IDD_DIALOG_OPTIONS_TABLE        356
#define IDB_BITMAP1                     360
#define IDR_TOOLBAR_MAIN2               361
#define IDR_TOOLBAR_MAIN                361
#define IDR_MENU1                       363
#define IDR_MENU_RECOMMENDER            363
#define IDR_MAIN_MENU                   364
#define IDD_DIALOG_MAIN                 368
#define IDB_TASKBAR_ALARM               369
#define IDD_DIALOG_CHANGE_PASSWORD      371
#define IDR_TOOLBAR_DSVIP               372
#define IDR_TOOLBAR_WIZ                 376
#define IDB_HOGA_CONTRACT_BUY1          377
#define IDB_HOGA_CONTRACT_SELL          377
#define IDR_MENU_BANKING_IO             378
#define IDR_MENU_QUERY                  379
#define IDR_MENU_TRADING                380
#define IDR_MENU_TRADING_STANDARD       381
#define IDR_MENU2                       382
#define IDR_MENU_SETTINGS               382
#define IDD_DIALOG_LEVERAGE             383
#define IDR_MENU_SETTINGS1              383
#define IDR_MENU_SETTINGS_MINI          383
#define IDR_MAIN_MENU_LHY               384
#define IDD_DIALOG2                     385
#define IDD_DIALOG_DKMSG                385
#define IDR_MAIN_MENU1                  385
#define IDR_MAIN_MENU_MINI              385
#define IDC_EDIT_LOSSCUT                1000
#define IDC_EDIT1                       1000
#define IDC_EDIT_EARNCUT                1001
#define IDC_EDIT_NAME                   1001
#define IDC_EDIT_VOL_2                  1001
#define IDC_EDIT2                       1001
#define IDC_EDIT_FF                     1001
#define IDC_GRID_HOGA                   1002
#define IDC_EDIT_PASSWORD               1002
#define IDC_EDIT_VOL_3                  1002
#define IDC_EDIT_AMOUNT_REQUEST         1002
#define IDC_GRID_CHE                    1003
#define IDC_GRID_MARKET_CONTRACT        1003
#define IDC_EDIT_VOL_4                  1003
#define IDC_EDIT_PASSWORD3              1003
#define IDC_EDIT_PREV                   1003
#define IDC_COMBO_CODE                  1004
#define IDC_EDIT_PASSWORD2              1004
#define IDC_EDIT_VOL_5                  1004
#define IDC_BUTTON_CODE_APPLY           1005
#define IDC_EDIT_EMAIL                  1005
#define IDC_EDIT_PRICE                  1006
#define IDC_EDIT_MOBILE                 1006
#define IDC_EDIT_VOLUME                 1007
#define IDC_EDIT_PHONE                  1007
#define IDC_COMBO_HOGA                  1008
#define IDC_EDIT_ADDRESS                1008
#define IDC_BUTTON_BUY                  1009
#define IDC_EDIT_BANK_OWNER             1009
#define IDC_BUTTON_SELL                 1010
#define IDC_EDIT_ORG_NO                 1011
#define IDC_BUTTON_CORRECTION           1012
#define IDC_BUTTON_CANCEL               1013
#define IDC_GRID_CHE2                   1020
#define IDC_GRID_JANGO                  1020
#define IDC_GRID_CONTRACT               1020
#define IDC_GRID_ORDER_PANEL            1020
#define IDC_GRID_OUTSTANDING_ORDER      1021
#define IDC_STATIC_PROFIT_REALIZE       1022
#define IDC_STATIC_PROFIT_EVAL          1023
#define IDC_TAB_MERCHANDISE             1024
#define IDC_BUTTON_MARKET_SELL          1025
#define IDC_BUTTON_MARKET_BUY           1026
#define IDC_BUTTON_ALL_LIQUID           1027
#define IDC_BUTTON_SELL_MIT_CANCEL      1028
#define IDC_BUTTON_SELL_CANCEL          1029
#define IDC_BUTTON_ALL_CANCEL           1030
#define IDC_BUTTON_BUY_MIT_CANCEL       1031
#define IDC_BUTTON_SELL_CANCEL2         1032
#define IDC_STATIC_ENABLE_SELL          1032
#define IDC_BUTTON_BUY_CANCEL           1033
#define IDC_TAB_INFO                    1034
#define IDC_TAB_STOP_ORDER              1034
#define IDC_TAB_SET_DISPLAY             1034
#define IDC_GRID_MIT                    1035
#define IDC_GRID_CUR_INFO               1036
#define IDC_GRID_TOTAL_CONTRACT         1037
#define IDC_GRID_CONTRACT_PROFIT        1037
#define IDC_SPIN_VOL                    1038
#define IDC_GRID_OUTSTANDING_ORDER2     1039
#define IDC_STATIC_ENABLE_BUY           1039
#define IDC_GRID_CLIENT                 1039
#define IDC_GRID_TOT_HOGA               1040
#define IDC_BUTTON_VOL1                 1041
#define IDC_GRID_ACCOUNT_BALANCE        1041
#define IDC_BUTTON_VOL2                 1042
#define IDC_GRID_PROFIT                 1042
#define IDC_BUTTON_VOL3                 1043
#define IDC_BUTTON_VOL5                 1044
#define IDC_BUTTON_VOL10                1045
#define IDC_BUTTON_VOL15                1046
#define IDC_BUTTON_EXPAND               1046
#define IDC_BUTTON_VOL20                1047
#define IDC_STATIC_REAL_EVAL            1048
#define IDC_STATIC_EVAL                 1049
#define IDC_CHECK_BIG_HOGA_HEIGHT       1050
#define IDC_COMBO_QUERY_FIELD           1050
#define IDC_TAB_MARKET_CONTRACT         1051
#define IDC_BUTTON_1HOGA_SELL           1051
#define IDC_CHECK_ONECLICK_ORDER        1052
#define IDC_EDIT_QUERY                  1052
#define IDC_TAB_SIMPLE_ORDER            1053
#define IDC_DKSPIN1                     1053
#define IDC_DKSPIN_VOLUME               1053
#define IDC_CHECK_LOSSCUT               1054
#define IDC_DATETIMEPICKER_BEGIN        1054
#define IDC_CHECK_EARNCUT               1055
#define IDC_DATETIMEPICKER_END          1055
#define IDC_SPIN_LOSSCUT                1056
#define IDC_SPIN_EARNCUT                1057
#define IDC_BUTTON_START                1057
#define IDC_EDIT_ACCOUNT                1058
#define IDC_BUTTON_1HOGA_BUY            1058
#define IDC_STATIC_COUNT                1058
#define IDC_DKSPIN_LOSSCUT              1058
#define IDC_BUTTON1                     1059
#define IDC_BUTTON_REQUEST              1059
#define IDC_BUTTON_QUERY                1059
#define IDC_BUTTON_SELECT_CODE          1059
#define IDC_BUTTON_APPLY                1059
#define IDC_BUTTON_UPDATE               1059
#define IDC_BUTTON_START2               1059
#define IDC_EDIT_ID                     1060
#define IDC_BUTTON_START3               1060
#define IDC_DKSPIN_EARNCUT              1060
#define IDC_BUTTON_QUERY2               1061
#define IDC_BUTTON_EXCEL                1061
#define IDC_CHECK1                      1061
#define IDC_COMBO_BANK                  1062
#define IDC_CHECK_TOOLTIP_SHOW          1062
#define IDC_BUTTON_ID_DUPLICATE_CHECK   1063
#define IDC_CHECK_CONTRACT_POPUP_SHOW   1063
#define IDC_BUTTON4                     1063
#define IDC_BUTTON_REGISTER             1064
#define IDC_EDIT_AMOUNT                 1064
#define IDC_EDIT_BANK                   1065
#define IDC_EDIT_BANK_ACCOUNT           1066
#define IDC_CHECK_VOICE_BUY_ORDER       1066
#define IDC_CHECK_VOICE_SELL_ORDER      1067
#define IDC_EDIT_AMOUNT2                1067
#define IDC_GRID                        1068
#define IDC_EDIT_MEMO                   1068
#define IDC_CHECK_VOICE_BUY_CANCEL      1068
#define IDC_EDIT_HEADER                 1069
#define IDC_CHECK_VOICE_SELL_CANCEL     1069
#define IDC_EDIT_BODY                   1070
#define IDC_CHECK_VOICE_BUY_CORRECTION  1070
#define IDC_EDIT_BODY2                  1071
#define IDC_CHECK_VOICE_SELL_CORRECTION 1071
#define IDC_DATE                        1072
#define IDC_CHECK_VOICE_BUY_CONTRACT    1072
#define IDC_CHECK_CONTRACT              1073
#define IDC_CHECK_VOICE_SELL_CONTRACT   1073
#define IDC_STATIC_DATE                 1074
#define IDC_DATE_BEGIN                  1075
#define IDC_CHECK_ACC_ORDER_ALL         1075
#define IDC_DATE_BEGIN2                 1076
#define IDC_DATE_END                    1076
#define IDC_CHECK_ACC_STOP_ORDER_CANCEL 1076
#define IDC_BUTTON_TO_EXCEL             1076
#define IDC_CHECK_ACC_MIT_ORDER_CANCEL  1077
#define IDC_CHECK_ACC_ALL_LIQUID        1078
#define IDC_EDIT_                       1079
#define IDC_EDIT_RCOMMENDER             1079
#define IDC_EDIT_RECOMMENDER            1079
#define IDC_CHECK_ACC_IMMEDIATE_ORDER   1079
#define IDC_CHECK_ACC_SIJANGA_BUY       1079
#define IDC_CONNECT                     1080
#define IDC_DATEEND2                    1080
#define IDC_BUTTON_CONNECT              1080
#define IDC_CHECK_ACC_SIJANGA_SELL      1080
#define IDC_STATIC_TITLE                1081
#define IDC_STATIC_BODY                 1082
#define IDC_STATIC1                     1083
#define IDC_STATIC2                     1084
#define IDC_STATIC3                     1085
#define IDC_STATIC4                     1086
#define IDC_STATIC_SELL                 1087
#define IDC_STATIC_BUY                  1088
#define IDC_STATIC_SEL_CODE             1089
#define IDC_STATIC_1                    1090
#define IDC_STATIC_GROUP_BANK           1091
#define IDC_STATIC_2                    1091
#define IDC_STATIC_GROUP_MEMO           1092
#define IDC_STATIC5                     1093
#define IDC_DATEBEGIN                   1095
#define IDC_DATEEND                     1096
#define IDC_RADIO1                      1101
#define IDC_RADIO2                      1102
#define IDC_RADIO3                      1103
#define IDC_BUTTON_QUERY_CLIENT         1104
#define ID_TABCTRL_MERCHANDISE          1105
#define IDC_COMBO_SYSKEY_ORDER_ALL      1106
#define IDC_TABCTRL_STOP                1106
#define IDC_COMBO_KEY_ORDER_ALL         1107
#define IDC_TABCTRL_CURRENT_INFO        1107
#define IDC_COMBO_SYSKEY_STOP_ORDER_CANCEL 1108
#define IDC_TABCTRL_CONTRACTS           1108
#define IDC_COMBO_KEY_STOP_ORDER_CANCEL 1109
#define IDC_COMBO_SYSKEY_MIT_ORDER_CANCEL 1110
#define IDC_COMBO_KEY_MIT_ORDER_CANCEL  1111
#define IDC_COMBO_SYSKEY_ALL_LIQUID     1112
#define IDC_COMBO_KEY_ALL_LIQUID        1113
#define IDC_COMBO_SYSKEY_IMMEDIATE_ORDER 1114
#define IDC_COMBO_KEY_IMMEDIATE_ORDER   1115
#define IDC_COMBO_SYSKEY_REFRESH        1116
#define IDC_COMBO_KEY_REFRESH           1117
#define IDC_CHECK_ORDER_CONFIRM_SHOW    1118
#define IDC_RADIO_HOGA_HEIGHT_FIX       1119
#define IDC_RADIO_HOGA_COUNT_FIX        1120
#define IDC_EDIT_VOL_1                  1121
#define IDC_STATIC_GROUP_1              1122
#define IDC_STATIC_GROUP_2              1123
#define IDC_STATIC_GROUP_3              1124
#define IDC_STATIC_GROUP_4              1125
#define IDC_STATIC_GROUP5               1126
#define IDC_STATIC_GROUP_5              1126
#define IDC_BUTTON_CLOSE                1127
#define IDC_BUTTON_VOL_1                1128
#define IDC_BUTTON_VOL_2                1129
#define IDC_BUTTON_VOL_3                1130
#define IDC_BUTTON_VOL_4                1131
#define IDC_BUTTON_VOL_5                1132
#define IDC_BUTTON_VOL_6                1133
#define IDC_BUTTON_VOL_7                1134
#define IDC_BUTTON_VOL_8                1135
#define IDC_TAB_CURRENT_INFO            1136
#define IDC_CHECK_ALWAYS_ON_TOP         1137
#define IDC_CHECK_STANDALONE            1138
#define IDC_STATIC_LOG                  1138
#define IDC_MENU_BAR                    1139
#define IDC_TOOL_BAR                    1140
#define IDC_BUTTON_MODIFY               1140
#define IDC_EDIT_NEW                    1141
#define IDC_EDIT_CONFIRM                1142
#define IDC_STATIC_USD                  1145
#define IDC_STATIC_KOSPI                1147
#define IDC_TAB_DISPLAY_SETTING         1150
#define IDC_TAB_CURRENT_PRICE           1151
#define IDC_TAB_CURRENT_PRICE2          1152
#define IDC_TAB_CONTRACTS               1152
#define IDC_BUTTON2                     1153
#define IDC_STATIC_RECOMMENDER          1154
#define IDC_BUTTON_FOREIGN_FUTURES_1    1161
#define IDC_BUTTON12                    1161
#define IDC_BUTTON_FOREIGN_FUTURES_2    1162
#define IDC_BUTTON_FOREIGN_FUTURES_3    1163
#define IDC_BUTTON_FOREIGN_FUTURES_4    1164
#define IDC_BUTTON_FOREIGN_FUTURES_5    1165
#define IDC_BUTTON_FOREIGN_FUTURES_6    1166
#define IDC_BUTTON_FOREIGN_FUTURES_7    1167
#define IDC_BUTTON_FOREIGN_FUTURES_8    1168
#define IDC_BUTTON_FOREIGN_FUTURES_9    1169
#define IDC_BUTTON_FOREIGN_FUTURES_10   1170
#define IDC_BUTTON_FOREIGN_FUTURES_R    1200
#define IDC_TAB                         1202
#define IDC_STATIC_12                   1205
#define IDC_BUTTON_WIZ_MAIN_RESERVED    1250
#define IDC_KOSPI_NAME                  1251
#define IDC_KOSPI                       1252
#define IDC_USD_NAME                    1253
#define IDC_USD                         1254
#define IDM_BANKING_IO                  1256
#define IDM_QUERY                       1257
#define IDM_RECOMMENDERS                1258
#define IDM_TRADING                     1261
#define IDC_EXPLORER                    1262
#define IDM_TRADING_STANDARD            1263
#define IDM_SETTINGS                    1264
#define IDC_COMBO_LEVERAGE              1266
#define IDC_STATIC_CUR_LEVERAGE         1267
#define IDC_STATIC_HELP                 1270
#define IDC_EDIT_MILEAGE                1271
#define IDC_STATIC_MIN_ENABLE           1272
#define IDC_EDIT_MILEAGE_REQUEST        1273
#define IDC_EDIT_MILEAGER_EXCHANGE      1273
#define IDC_GRID_MARKET_CONTRACT2       1273
#define IDC_STATIC_FF                   1274
#define IDC_STATIC_F                    1275
#define IDC_EDIT_F                      1276
#define IDC_GRID_OPTIONS                1277
#define IDC_GRID_OPTIONS2               1278
#define IDC_GRID_FOREIGN_FUTURES        1278
#define IDD_DIALOG_MSG                  6000
#define IDC_EDIT_MSG_BODY               6000
#define IDC_EDIT_MSG_TITLE              6001
#define IDD_DIALOG_LOGIN                6002
#define IDC_EDIT_LOGIN_ID               6003
#define IDC_EDIT_LOGIN_PASSWORD         6004
#define IDD_DIALOG_RECOMMENDER_EACHDAY_PROFIT 6004
#define IDC_CHECK_SAVE_ID               6005
#define IDD_DIALOG_RECOMMENDER_MEMBERS_ACTION_LOG 6005
#define IDD_DIALOG_PREFERENCES          6006
#define IDD_DIALOG_REQ                  6007
#define IDD_DIALOG_ORDER_ACTION_LOG     6008
#define IDD_DIALOG_FOREIGN_FUTURES_CODE 6009
#define IDD_DIALOG_FAST_TRADE1          6010
#define IDD_DIALOG_FAST_TRADE_DSVIP     6010
#define IDD_DIALOG_FAST_TRADE_WIZ       6014
#define IDD_DIALOG_FAST_TRADE           6014
#define IDD_DIALOG_WIZ_MAIN             6015
#define IDD_DIALOG_WEB_BROWSER          6016
#define IDD_DIALOG_TKM_MAIN             6017
#define IDD_DIALOG_EXCHANGE_MILEAGE     6018
#define IDD_DIALOG_OVERNIGHT_REQUEST    6019
#define IDD_DIALOG_RECOMMENDERS_CLIENT_TOTAL_PROFIT 6020
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_EDIT_WINDOWS_NUMBER          32771
#define ID_RBN_BTN_DUMMY                32772
#define ID_RBN_BTN_FAST_TRADING         32773
#define ID_RBN_BTN_NOTICES              32774
#define ID_RBN_BTN_ORDER_HISTORY        32775
#define ID_RBN_BTN_EACH_DAY_PROFIT      32776
#define ID_RBN_BTN_BANKING_IO_HISTORY   32778
#define ID_RBN_BTN_USER_ACTION_LOG      32779
#define ID_RBN_BTN_SYSTEM_LOG           32780
#define ID_RBN_BTN_BANKING_WITHDRAW     32782
#define ID_RBN_BTN_BANKING_DEPOSIT      32783
#define ID_RBN_BTN_PREFERENCES          32784
#define ID_RBN_BTN_OPTIONS_TABLE        32785
#define ID_RBN_BTN_RCMD_MEMBERS_PROFIT  32786
#define ID_RBN_BTN_RCMD_PERIOD_PROFIT   32787
#define ID_RBN_BTN_RCMD_MEMBER_ACTION_LOG 32788
#define ID_RIBBON_COMMAND_RESERVED      32899
#define IDC_STATIC_WND_NUMBER           32900
#define ID_TOOLEDIT_WND_FIND            32901
#define ID_FAST_TRADING                 32902
#define ID_BANKING_WITHDRAW             32903
#define ID_BANKING_DEPOSIT              32904
#define ID_EACH_DAY_PROFIT              32905
#define ID_ORDER_HISTORY                32906
#define ID_BANKING_IO_HISTORY           32907
#define ID_USER_ACTION_LOG              32908
#define ID_NOTICES                      32909
#define ID_PREFERENCES                  32910
#define ID_OPTIONS_TABLE                32911
#define ID_RCMD_MEMBERS_PROFIT          32912
#define ID_RCMD_PERIOD_PROFIT           32913
#define ID_RCMD_MEMBER_ACTION_LOG       32914
#define ID_DUMMY                        32916
#define ID_ORDER_ACTION_LOG             32917
#define ID_SYSTEM_LOG                   32918
#define ID_RECOMMENDER                  32919
#define ID_CHANGE_PASSWORD              32920
#define ID_TRDSTD_1                     32922
#define ID_TRDSTD_2                     32923
#define ID_TRDSTD_3                     32924
#define ID_TRDSTD_4                     32925
#define ID_TRDSTD_5                     32926
#define ID_RCMD_CLIENT_INFO             32927
#define ID_RCMD_CLIENT_TOTAL_PROFIT     32928
#define IDM_FAST_TRADING                32950
#define IDM_BANKING_WITHDRAW            32951
#define IDM_BANKING_DEPOSIT             32952
#define IDM_EACH_DAY_PROFIT             32953
#define IDM_ORDER_HISTORY               32954
#define IDM_BANKING_IO_HISTORY          32955
#define IDM_USER_ACTION_LOG             32956
#define IDM_NOTICES                     32957
#define IDM_PREFERENCES                 32958
#define IDM_OPTIONS_TABLE               32959
#define IDM_RCMD_MEMBERS_PROFIT         32960
#define IDM_RCMD_PERIOD_PROFIT          32961
#define IDM_RCMD_MEMBER_ACTION_LOG      32962
#define IDM_DUMMY                       32963
#define IDM_ORDER_ACTION_LOG            32964
#define IDM_SYSTEM_LOG                  32965
#define IDM_RECOMMENDER                 32966
#define IDM_CHANGE_PASSWORD             32967
#define IDM_TRDSTD_1                    32968
#define IDM_TRDSTD_2                    32969
#define IDM_TRDSTD_3                    32970
#define IDM_TRDSTD_4                    32971
#define IDM_TRDSTD_5                    32972
#define IDM_TRDSTD_RESERVED             32980
#define IDM_LEVERAGE                    32981
#define IDM_EXCHANGE_MILEAGE            32982
#define IDM_OVERNIGHT_REQUEST           32983
#define IDM_RCMD_CLIENT_INFO            32984
#define IDM_RCMD_CLIENT_TOTAL_PROFIT    32985
#define ID_TOOLBAR_BUTTON_RESERVED      33000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        386
#define _APS_NEXT_COMMAND_VALUE         33001
#define _APS_NEXT_CONTROL_VALUE         1278
#define _APS_NEXT_SYMED_VALUE           317
#endif
#endif
